name: klin_dart
description: A starting point for Dart libraries or applications.
version: 1.0.0
# repository: https://github.com/my_org/my_repo

environment:
  sdk: ^3.5.4

# Add regular dependencies here.
dependencies:
  custom_lint_builder: ^0.6.8
  analyzer: ^6.7.0

dev_dependencies:
  lints: ^4.0.0
  test: ^1.24.0
