name: klin_dart
description: KlinDart is a collection of opinionated custom lint rules for Dart and Flutter projects. It focuses on improving code **readability**, **maintainability**, and **scalability** by enforcing architectural and stylistic best practices.
version: 1.0.0
repository: https://github.com/kevinchrist20/klin_dart

environment:
  sdk: ^3.6.0

# Add regular dependencies here.
dependencies:
  custom_lint_builder: ^0.7.5
  analyzer: ^7.6.0

dev_dependencies:
  lints: ^5.1.1
  test: ^1.24.0
